package geekbrains.ENUM;

public enum Functionality {
    GET_CURRENT_WEATHER,
    GET_WEATHER_IN_NEXT_2_DAYS,
    GET_WEATHER_IN_NEXT_3_DAYS,
    GET_WEATHER_IN_NEXT_4_DAYS,
    GET_WEATHER_IN_NEXT_5_DAYS,
    GET_WEATHER_IN_NEXT_6_DAYS,
    GET_WEATHER_IN_NEXT_7_DAYS
}
